name: Terraform Apply
on:
  push:
    branches:
      - dev
      - beta

env:
  TERRAFORM_VERSION: "1.4.6"
  TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_region: ${{ secrets.AWS_REGION }}

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Terraform
        run: |
          tf_version=$TERRAFORM_VERSION
          wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
          unzip terraform_"$tf_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform Apply
        env:
          CURRENT_ENV: ${{ github.ref_name }}
        run: |
          cd env/$CURRENT_ENV
          terraform init -input=false
          terraform validate
          terraform apply -auto-approve -input=false
